package lexical;

public enum TokenCategory {

	MAJOR, ID, TEMPTY, TINT, TLONG, TLOGIC, TCHAR, TCCHAR, TDEC, ESCBEGIN, ESCEND,
	PARAMBEGIN, PARAMEND, ARRAYBEGIN, ARRAYEND, COMBEGIN, COMEND, TERM,
	CONSTNUMINT, CONSTNUMDEC, CONSTLOGIC, CONSTCHAR, CONSTCCHAR,
	PRIF, PRELSE, PRELSEIF, PRITERATOR, PRDO, PRWHILE, OPLOGICAND, OPLOGICOR, OPNEGLOGIC,
	OPARITADIT, OPARITMULT, OPARITEXP, OPNEGUN, OPREL, OPATRIB, OPCONC, UNKNOWN
	
}
