package lexical;

public enum TokenCategory {

		MAJOR, ID, TEMPTY, TINT, TLONG, TLOGIC, TCHAR, TCCHAR, TDEC, ESCBEGIN, ESCEND,
		PARAMBEGIN, PARAMEND, ARRAYBEGIN, ARRAYEND, COMBEGIN, COMEND, TERM, CONSTNUMINT,
		CONSTNUMDEC, CONSTLOGIC, CONSTCHAR, CONSTCCHAR, PRIF, PRELSE, PRELSEIF, PRITERATOR, PRDO,
		PRWHILE, OPNEGLOGIC, OPLOGIC, OPARITADIT, OPARITMULT, OPARITEXP, OPNEGUN, OPREL,
		OPCONC		
	
}
